### PR TITLE
show timeseries

### PR DESCRIPTION
**Pull request by mbertani**
It would be nice to be able to produce graphs for anomaly detection like here: https://www.elastic.co/blog/implementing-a-statistical-anomaly-detector-part-2 

Two series functions are suggested based from code by Zachary Tong in the link above: showifgreater and showifsmaller.

To test these functions in kibaba 4.4.2, you have to:
- Delete everything under \<kibana\>\\optimize\bundles
- Copy the functions manually to \<kibana\>\\installedPlugins\timelion\series_functions
- Start kibana

### CODE REVIEW

**Comment by rashidkpc** [comment]
You can use the `.condition()` function to accomplish this. @polyfractal wrote that before `.condition()` was available, but mentioned he would update the blog post

https://github.com/elastic/timelion/blob/master/FUNCTIONS.md#condition

**Comment by polyfractal** [comment]
Yep, sorry about that @mbertani, updating the article has been on my todo list since the `.condition()` function was added.  I'll try to do that soon!

**Comment by mbertani** [comment]
I see. Somehow I missed ```.condition()``` in the last releases. I have played a bit with it, and there seems to be a strange behavior at the beginning of the series when I use it together with ```.movingaverage()``` and ```.movingstd()```:
showifgreater_vs_condition

The query on chart 2 is:
``` .es(q='THEFT'),.es(q='THEFT').showifgreater(.es(q='THEFT').movingaverage(7,'left').sum(.es(q='THEFT').movingstd(7).multiply(3))).bars(3).label(outliers) ```

The query on chart 3 is:
``` .es(q='THEFT'),.es(q='THEFT').condition(operator='gt',if=.es(q='THEFT').movingaverage(7,'left').sum(.es(q='THEFT').mvstd(7).multiply(3)), then=.es(q='THEFT'),else=0).label(outliers).bars(3)```
I wasn't expecting the bars at the beginning to show up. It's related to the size of the window and the unavailable data at those times. Is there a trick to fix this? Something like "extend my series with this value if unavailable data for comparison"?
I tried to trick it by doing something like this:
```.es(q='THEFT').min(0).max(.es(q='THEFT').movingaverage(7,'left').sum(.es(q='THEFT').mvstd(7).multiply(3)))``` but the support of the series shrinks after i chain ```.max(...)```.

But anyway, this is a minor bug. We can disregard this pull request since ```.condition()``` does the job and it is more flexible. 

No worries @polyfractal ! It is a great article!

**Comment by rashidkpc** [comment]
I'm pretty sure whats happening on chart 3 is the result of `if=.es(q='THEFT').movingaverage(7,'left')`. Because you passed `position=left` the moving average function used the left side values for averaging, resulting in 7 null values on the left side of the chart.

So if is checking to see if() is evaluating `.es(q='THEFT') > null`. Timelion basically treats `null` as *Crap, i dunno what that means*. You can fix it by filling the `null`s with 0s. So change `.es(q='THEFT').movingaverage(7,'left')` to `.es(q='THEFT').movingaverage(7,'left').if(eq, null, 0)` and that should get rid of those leading red bars.

**Comment by mbertani** [comment]
Thank you for your answer @rashidkpc ! Sorry for my delay, easter vacations got in the way.

I found out that you have to do a bit more than that for the outlier detector to work. Here is the recipe if someone else is also interested:
image

1st query:
```.es(*),.es(*).condition(gt,.es(*).movingaverage(7,'left').if(eq, null, 0).sum(.es(*).mvstd(7).if(eq, null, 0).multiply(3)),.es(*),0).label(outliers).bars(3)```
The bars are still there. The reason is that we put zeros at the beginning of the time series. Thus when we do the comparison, the nonzero values of the original series win over the zeroes we added. But it can easily be fixed by using the original series in the first if-statement instead of zero. Look at the second query.
2nd query:
``` .es(*),.es(*).condition(gt,.es(*).movingaverage(7,'left').if(eq, null, .es(*)).sum(.es(*).mvstd(7).if(eq, null, 0).multiply(3)),.es(*),0).label(outliers).bars(3)```

The 3rd query just shows also the series we are comparing against to illustrate why the suggestion works. I just changed the order of the comparison, since it was easier to plot:
```.es(*),.es(*).movingaverage(7,'left').if(eq, null, .es(*)).sum(.es(*).mvstd(7).if(eq, null, 0).multiply(3)).condition(lt,.es(*),.es(*),0).label(outliers).bars(3),.es(*).movingaverage(7,'left').if(eq, null, .es(*)).sum(.es(*).mvstd(7).if(eq, null, 0).multiply(3)).label('full graph')```

**Comment by rashidkpc** [comment]
wow, nicely done!

**Comment by mbertani** [comment]
Thanks! :)

**Pull request closed without merging**
